# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Usr Reference', kernelModule='usr_datum', kernelFunction='datumPlaneCoord',
                      includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgHorizontalFrame(name='HFrame_1', p='DialogBox',
                   layout='0', pl=0, pr=0, pt=0, pb=0)
RsgTextField(p='HFrame_1', fieldType='String', ncols=12,
             labelText='Model:', keyword='locModel', default='Model-1')
RsgTextField(p='HFrame_1', fieldType='String', ncols=12,
             labelText='Part:', keyword='locPart', default='Part-1')
dialogBox.show()
